#! /bin/sh
#
# Stop on error and output every command before executing it
set -ex

echo "[cibuild] started at..."
date "+%H:%M:%S"

export RAILS_ENV="test"
export RACK_ENV="test"

hostname
rbenv local 2.3.0
bundle install --local

# Linting with pronto
# 
# On CI the access token will be set to comment on Github
if [ -n "$GITHUB_ACCESS_TOKEN" ]; then
  # Only run pronto if part of the Gemfile
  if bundle list | grep -q pronto; then
    bundle exec pronto run -c "origin/develop" -f github
  fi
fi
# run tests
echo "[cibuild] Running tests ..."
date "+%H:%M:%S"

bundle exec rake
